version: '3.7'

services:
  db_postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    ports:
      - 3333:3333 # Application
      - 9229:9229 # Debug
    volumes:
      - .:/usr/app
    links:
      - db_postgres
    depends_on:
      - db_postgres

volumes:
  pgdata:
    driver: local
